<?php
// This immediately jumps to "contact created," and doesn't
// present the form.  I think you need some kind of flag
// that says whether the form has been submitted, not one
// that checks one of the field variables.  See how Nixon does this.
  require_once 'header.php';

	// initialize the variables
  $first    = $middle   = $last = $phone_1 = $phone_2 =
	$street_1 = $street_2 = $city = $state   = $zip     =
	$notes    = $created  = '';
  
  // query generated by the form entry
	$queryString = 'INSERT INTO contacts
	  ( user, first, middle, last, phone_1, phone_2,
		   street_1, street_2, city, state, zip, notes)
	  VALUES
	  (:user,:first,:middle,:last,:phone_1,:phone_2,
		  :street_1,:street_2,:city,:state,:zip,:notes)';

  // assigning form entries to the variables
	$user = $_SESSION['user'];
	$first = $_POST['first'];
	$middle = $_POST['middle']; 
	$last = $_POST['last'];
	$phone_1 = $_POST['phone_1'];
	$phone_2 = $_POST['phone_2'];
	$street_1 = $_POST['street_1'];
	$street_2 = $_POST['street_2'];
	$city = $_POST['city'];
	$state = $_POST['state'];
	$zip = $_POST['zip'];
	$notes = $_POST['notes'];

	// execute the database query
	// put the result into $query
	if ( $last == '' ) {
	  echo "Please enter new contact's information<br>";
		echo <<<_END
			<form method='post' action='newKontakt.php'>
				First Name
					<input type='text' maxlength='16'
					  name='first'><br>
				Middle Name
					<input type='text' maxlength='16'
					  name='middle'><br>
				Last Name
					<input type='text' maxlength='16'
					  name='last'><br>
				Phone Number
					<input type='text' maxlength='16'
					  name='phone_1'><br>
				Alternate Phone
					<input type='text' maxlength='16'
					  name='phone_2'><br>
				Address
					<input type='text' maxlength='16'
					  name='street_1'><br>
				Apartment, etc.
					<input type='text' maxlength='16'
					  name='street_2'><br>
				City
					<input type='text' maxlength='16'
					  name='city'><br>
				State
					<input type='text' maxlength='2'
					  name='state'><br>
				Zipcode
					<input type='text' maxlength='16'
					  name='zip'><br>
				Notes
					<textarea maxlength='4096'
					  name='notes'></textarea><br>
				<input type='submit' value='Create Contact'><br>
			</form>
_END;
	}
	else {
		try {
			$query = $konnection->prepare($queryString);

			$query->bindParam('user', $user, PDO::PARAM_INT);
			$query->bindParam('first', $first, PDO::PARAM_INT);
			$query->bindParam('middle', $middle, PDO::PARAM_INT);
			$query->bindParam('last', $last, PDO::PARAM_INT);
			$query->bindParam('phone_1', $phone_1, PDO::PARAM_INT);
			$query->bindParam('phone_2', $phone_2, PDO::PARAM_INT);
			$query->bindParam('street_1', $street_1, PDO::PARAM_INT);
			$query->bindParam('street_2', $street_2, PDO::PARAM_INT);
			$query->bindParam('city', $city, PDO::PARAM_INT);
			$query->bindParam('state', $state, PDO::PARAM_INT);
			$query->bindParam('zip', $zip, PDO::PARAM_INT);
			$query->bindParam('notes', $notes, PDO::PARAM_INT);

			$query->execute();
      
			echo "<br>New Contact Created<br>";
			echo "Click <a href='view.php'>here</a> to return to your contacts list.";
		}
		catch( PDOException $e ) {
			echo $sql."<br>".$e->getMessage();
		}
	} // end else

?>
