<?php
// This immediately jumps to "contact created," and doesn't
// present the form.  I think you need some kind of flag
// that says whether the form has been submitted, not one
// that checks one of the field variables.  See how Nixon does this.
  require_once 'header.php';

	// initialize the variables
  $first    = $middle   = $last = $phone_1 = $phone_2 =
	$street_1 = $street_2 = $city = $state   = $zip     =
	$notes    = $created  = '';
  
  // query generated by the form entry
	$queryString = 'INSERT INTO contacts
	  ( user, first, middle, last, phone_1, phone_2,
		   street_1, street_2, city, state, zip, notes)
	  VALUES
	  (:user,:first,:middle,:last,:phone_1,:phone_2,
		  :street_1,:street_2,:city,:state,:zip,:notes)';

  // assigning form entries to the variables
	$user = $_SESSION['user'];
	$first = $_POST['first'];
	$middle = $_POST['middle']; 
	$last = $_POST['last'];
	$phone_1 = $_POST['phone_1'];
	$phone_2 = $_POST['phone_2'];
	$street_1 = $_POST['street_1'];
	$street_2 = $_POST['street_2'];
	$city = $_POST['city'];
	$state = $_POST['state'];
	$zip = $_POST['zip'];
	$notes = $_POST['notes'];

	// execute the database query
	// put the result into $query
	if ( $last == '' ) {
	  echo "Please enter new contact's information<br>";
		echo <<<_END
			<form method='post' action='newKontakt.php'>
				<table class='contact'>
				  <tr>
						<td>First Name</td>
						<td><input class='field' type='text' maxlength='16'
							name='first'>
						</td>
					</tr>
					<tr>
						<td>Middle Name</td>
						<td><input class='field' type='text' maxlength='16'
							name='middle'>
						</td>
					</tr>
					<tr>
						<td>Last Name</td>
						<td><input class='field' type='text' maxlength='16'
							name='last'>
						</td>
					</tr>
					<tr>
						<td>Phone Number</td>
						<td><input class='field' type='text' maxlength='10'
							name='phone_1'>
						</td>
					</tr>
					<tr>
						<td>Alternate Phone</td>
						<td><input class='field' type='text' maxlength='10'
							name='phone_2'>
						</td>
					</tr>
					<tr>
						<td>Address</td>
						<td><input class='field' type='text' maxlength='16'
							name='street_1'>
						</td>
					</tr>
					<tr>
						<td>Apartment, etc.</td>
						<td><input class='field' type='text' maxlength='16'
							name='street_2'>
						</td>
					</tr>
					<tr>
						<td>City</td>
						<td><input class='field' type='text' maxlength='16'
							name='city'>
						</td>
					</tr>
					<tr>
						<td>State</td>
						<td><input class='field' type='text' maxlength='2'
							name='state'>
						</td>
					</tr>
					<tr>
						<td>Zipcode</td>
						<td><input class='field' type='text' maxlength='16'
							name='zip'>
						</td>
					</tr>
					<tr>
						<td>Notes</td>
						<td><textarea class='field' maxlength='4096'
							name='notes'></textarea>
						</td>
					</tr>
					<tr>
						<td><input type='submit'
						     value='Create Contact'>
						</td>
					</tr>
				</table>
			</form>
_END;
	}
	else {
		try {
			$query = $konnection->prepare($queryString);

			$query->bindParam('user', $user, PDO::PARAM_INT);
			$query->bindParam('first', $first, PDO::PARAM_INT);
			$query->bindParam('middle', $middle, PDO::PARAM_INT);
			$query->bindParam('last', $last, PDO::PARAM_INT);
			$query->bindParam('phone_1', $phone_1, PDO::PARAM_INT);
			$query->bindParam('phone_2', $phone_2, PDO::PARAM_INT);
			$query->bindParam('street_1', $street_1, PDO::PARAM_INT);
			$query->bindParam('street_2', $street_2, PDO::PARAM_INT);
			$query->bindParam('city', $city, PDO::PARAM_INT);
			$query->bindParam('state', $state, PDO::PARAM_INT);
			$query->bindParam('zip', $zip, PDO::PARAM_INT);
			$query->bindParam('notes', $notes, PDO::PARAM_INT);

			$query->execute();
      
			echo "<div class='main'>" .
			     "New Contact Created<br>" .
			     "Click <a href='view.php'>here</a> " .
					 "to return to your contacts list." .
					 "</div>";
		}
		catch( PDOException $e ) {
			echo $sql."<br>".$e->getMessage();
		}
	} // end else

?>
